INSERT INTO categories_locals ( name, description) VALUES
( 'telecommunications', 'hermosa y bonita'),
('Tecnología', 'Productos y servicios relacionados con tecnología...'),
('Entretenimiento', 'Opciones de diversión y entretenimiento, como ...'),
('Restaurantes', 'Establecimientos de comida y bebida, desde co...'),
('Moda', 'Ropa, calzado y accesorios de moda para todas...'),
('Salud y Bienestar', 'Servicios y productos relacionados con la salud,...'),
('Educación', 'Cursos, talleres y recursos educativos para el a...'),
('Hogar y Decoración', 'Artículos para el hogar, muebles y accesorios d...'),
('Deportes', 'Equipos, accesorios y actividades relacionadas ...'),
('Arte y Cultura', 'Eventos, exposiciones y productos relacionados...'),
('Viajes y Turismo', 'Servicios y productos para planificar viajes y ex...');

INSERT INTO categories_events (name)
VALUES 
    ('Bebidas'),
    ('Música'),
    ('Gastronomía'),
    ('Arte'),
    ('Deportes'),
    ('Tecnología'),
    ('Cine'),
    ('Teatro'),
    ('Literatura'),
    ('Moda'),
    ('Fotografía'),
    ('Danza'),
    ('Conferencias'),
    ('Festivales'),
    ('Cultura'),
    ('Naturaleza'),
    ('Viajes'),
    ('Educación'),
    ('Salud y Bienestar'),
    ('Ofertas');